spring:
  jpa.show-sql: true
  jpa:
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changeLog-dev.xml

logging.level.org.hibernate.SQL: debug
logging.level.org.hibernate.type.descriptor.sql: trace